#! /bin/bash
set -e
repository=nexus.xxxxxx.com.cn:5000
yarn_image=${repository}/common/ubuntu-yarn-chrome:1.0

docker run --rm -e "NODE_ENV=dev" -v $(pwd):/app -v /tmp/yarn:/yarn -v /tmp/mobile_modules:/app/node_modules -w /app ${yarn_image} sh -c "./test.sh && chown -R 1000:1000 public/"
